SEED_WORDS = [
    {
        "word": "resilient",
        "word_type": "adjective",
        "phonetic": "/rɪˈzɪliənt/",
        "english_definition": "Able to recover quickly after difficulty or pressure.",
        "uzbek_definition": "Qiyinchilik yoki bosimdan keyin tez tiklana oladigan.",
        "english_example": "She stayed resilient during a difficult year.",
        "uzbek_example": "U qiyin yil davomida bardoshli bo'lib qoldi.",
        "level": "B2",
    },
    {
        "word": "clarify",
        "word_type": "verb",
        "phonetic": "/ˈklarɪfaɪ/",
        "english_definition": "To make something easier to understand.",
        "uzbek_definition": "Biror narsani tushunarliroq qilish, aniqlashtirish.",
        "english_example": "Could you clarify the last sentence?",
        "uzbek_example": "Oxirgi gapni aniqlashtirib bera olasizmi?",
        "level": "B1",
    },
    {
        "word": "deliberate",
        "word_type": "adjective",
        "phonetic": "/dɪˈlɪbərət/",
        "english_definition": "Done carefully and intentionally.",
        "uzbek_definition": "O'ylab, ataylab va ehtiyotkorlik bilan qilingan.",
        "english_example": "His answer was calm and deliberate.",
        "uzbek_example": "Uning javobi xotirjam va o'ylangan edi.",
        "level": "B2",
    },
    {
        "word": "improve",
        "word_type": "verb",
        "phonetic": "/ɪmˈpruːv/",
        "english_definition": "To become better or make something better.",
        "uzbek_definition": "Yaxshilanish yoki biror narsani yaxshilash.",
        "english_example": "Daily reading can improve your vocabulary.",
        "uzbek_example": "Har kuni o'qish lug'atingizni yaxshilashi mumkin.",
        "level": "A2",
    },
    {
        "word": "reliable",
        "word_type": "adjective",
        "phonetic": "/rɪˈlaɪəbl/",
        "english_definition": "Someone or something that can be trusted.",
        "uzbek_definition": "Ishonish mumkin bo'lgan odam yoki narsa.",
        "english_example": "He is a reliable friend.",
        "uzbek_example": "U ishonchli do'st.",
        "level": "B1",
    },
    {
        "word": "approach",
        "word_type": "noun",
        "phonetic": "/əˈprəʊtʃ/",
        "english_definition": "A way of dealing with a problem or task.",
        "uzbek_definition": "Muammo yoki vazifaga yondashish usuli.",
        "english_example": "Her approach to learning is practical.",
        "uzbek_example": "Uning o'rganishga yondashuvi amaliy.",
        "level": "B1",
    },
    {
        "word": "consistent",
        "word_type": "adjective",
        "phonetic": "/kənˈsɪstənt/",
        "english_definition": "Happening in the same way over time.",
        "uzbek_definition": "Vaqt davomida bir xil tarzda davom etadigan.",
        "english_example": "Consistent practice brings strong results.",
        "uzbek_example": "Muntazam mashq kuchli natijalar beradi.",
        "level": "B1",
    },
    {
        "word": "evidence",
        "word_type": "noun",
        "phonetic": "/ˈevɪdəns/",
        "english_definition": "Facts or information that show something is true.",
        "uzbek_definition": "Biror narsaning rostligini ko'rsatadigan dalil yoki ma'lumot.",
        "english_example": "The report gives clear evidence.",
        "uzbek_example": "Hisobot aniq dalillar beradi.",
        "level": "B2",
    },
    {
        "word": "achieve",
        "word_type": "verb",
        "phonetic": "/əˈtʃiːv/",
        "english_definition": "To succeed in doing something after effort.",
        "uzbek_definition": "Mehnat orqali biror narsaga erishish.",
        "english_example": "You can achieve fluency with steady practice.",
        "uzbek_example": "Muntazam mashq bilan ravonlikka erisha olasiz.",
        "level": "B1",
    },
    {
        "word": "curious",
        "word_type": "adjective",
        "phonetic": "/ˈkjʊəriəs/",
        "english_definition": "Wanting to know or learn something.",
        "uzbek_definition": "Bilishga yoki o'rganishga qiziqadigan.",
        "english_example": "Curious students ask better questions.",
        "uzbek_example": "Qiziquvchan talabalar yaxshiroq savollar beradi.",
        "level": "A2",
    },
    {
        "word": "precise",
        "word_type": "adjective",
        "phonetic": "/prɪˈsaɪs/",
        "english_definition": "Exact and accurate.",
        "uzbek_definition": "Aniq va xatosiz.",
        "english_example": "Use precise words in formal writing.",
        "uzbek_example": "Rasmiy yozishda aniq so'zlardan foydalaning.",
        "level": "B2",
    },
    {
        "word": "benefit",
        "word_type": "noun",
        "phonetic": "/ˈbenɪfɪt/",
        "english_definition": "An advantage or helpful result.",
        "uzbek_definition": "Foyda, afzallik yoki yordam beradigan natija.",
        "english_example": "One benefit of reading is a richer vocabulary.",
        "uzbek_example": "O'qishning bir foydasi boyroq lug'atdir.",
        "level": "A2",
    },
]
