import type { Word } from "./types";

export const DAILY_FREE_LIMIT = 10;

export const words: Word[] = [
  {
    id: 1,
    word: "resilient",
    wordType: "adjective",
    phonetic: "/rɪˈzɪliənt/",
    englishDefinition: "Able to recover quickly after difficulty or pressure.",
    uzbekDefinition: "Qiyinchilik yoki bosimdan keyin tez tiklana oladigan.",
    englishExample: "She stayed resilient during a difficult year.",
    uzbekExample: "U qiyin yil davomida bardoshli bo'lib qoldi.",
    level: "B2",
  },
  {
    id: 2,
    word: "clarify",
    wordType: "verb",
    phonetic: "/ˈklarɪfaɪ/",
    englishDefinition: "To make something easier to understand.",
    uzbekDefinition: "Biror narsani tushunarliroq qilish, aniqlashtirish.",
    englishExample: "Could you clarify the last sentence?",
    uzbekExample: "Oxirgi gapni aniqlashtirib bera olasizmi?",
    level: "B1",
  },
  {
    id: 3,
    word: "deliberate",
    wordType: "adjective",
    phonetic: "/dɪˈlɪbərət/",
    englishDefinition: "Done carefully and intentionally.",
    uzbekDefinition: "O'ylab, ataylab va ehtiyotkorlik bilan qilingan.",
    englishExample: "His answer was calm and deliberate.",
    uzbekExample: "Uning javobi xotirjam va o'ylangan edi.",
    level: "B2",
  },
  {
    id: 4,
    word: "improve",
    wordType: "verb",
    phonetic: "/ɪmˈpruːv/",
    englishDefinition: "To become better or make something better.",
    uzbekDefinition: "Yaxshilanish yoki biror narsani yaxshilash.",
    englishExample: "Daily reading can improve your vocabulary.",
    uzbekExample: "Har kuni o'qish lug'atingizni yaxshilashi mumkin.",
    level: "A2",
  },
  {
    id: 5,
    word: "reliable",
    wordType: "adjective",
    phonetic: "/rɪˈlaɪəbl/",
    englishDefinition: "Someone or something that can be trusted.",
    uzbekDefinition: "Ishonish mumkin bo'lgan odam yoki narsa.",
    englishExample: "He is a reliable friend.",
    uzbekExample: "U ishonchli do'st.",
    level: "B1",
  },
  {
    id: 6,
    word: "approach",
    wordType: "noun",
    phonetic: "/əˈprəʊtʃ/",
    englishDefinition: "A way of dealing with a problem or task.",
    uzbekDefinition: "Muammo yoki vazifaga yondashish usuli.",
    englishExample: "Her approach to learning is practical.",
    uzbekExample: "Uning o'rganishga yondashuvi amaliy.",
    level: "B1",
  },
  {
    id: 7,
    word: "consistent",
    wordType: "adjective",
    phonetic: "/kənˈsɪstənt/",
    englishDefinition: "Happening in the same way over time.",
    uzbekDefinition: "Vaqt davomida bir xil tarzda davom etadigan.",
    englishExample: "Consistent practice brings strong results.",
    uzbekExample: "Muntazam mashq kuchli natijalar beradi.",
    level: "B1",
  },
  {
    id: 8,
    word: "evidence",
    wordType: "noun",
    phonetic: "/ˈevɪdəns/",
    englishDefinition: "Facts or information that show something is true.",
    uzbekDefinition: "Biror narsaning rostligini ko'rsatadigan dalil yoki ma'lumot.",
    englishExample: "The report gives clear evidence.",
    uzbekExample: "Hisobot aniq dalillar beradi.",
    level: "B2",
  },
  {
    id: 9,
    word: "achieve",
    wordType: "verb",
    phonetic: "/əˈtʃiːv/",
    englishDefinition: "To succeed in doing something after effort.",
    uzbekDefinition: "Mehnat orqali biror narsaga erishish.",
    englishExample: "You can achieve fluency with steady practice.",
    uzbekExample: "Muntazam mashq bilan ravonlikka erisha olasiz.",
    level: "B1",
  },
  {
    id: 10,
    word: "curious",
    wordType: "adjective",
    phonetic: "/ˈkjʊəriəs/",
    englishDefinition: "Wanting to know or learn something.",
    uzbekDefinition: "Bilishga yoki o'rganishga qiziqadigan.",
    englishExample: "Curious students ask better questions.",
    uzbekExample: "Qiziquvchan talabalar yaxshiroq savollar beradi.",
    level: "A2",
  },
  {
    id: 11,
    word: "precise",
    wordType: "adjective",
    phonetic: "/prɪˈsaɪs/",
    englishDefinition: "Exact and accurate.",
    uzbekDefinition: "Aniq va xatosiz.",
    englishExample: "Use precise words in formal writing.",
    uzbekExample: "Rasmiy yozishda aniq so'zlardan foydalaning.",
    level: "B2",
  },
  {
    id: 12,
    word: "benefit",
    wordType: "noun",
    phonetic: "/ˈbenɪfɪt/",
    englishDefinition: "An advantage or helpful result.",
    uzbekDefinition: "Foyda, afzallik yoki yordam beradigan natija.",
    englishExample: "One benefit of reading is a richer vocabulary.",
    uzbekExample: "O'qishning bir foydasi boyroq lug'atdir.",
    level: "A2",
  },
];


